create table if not exists category (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    number_choose int not null default 0
);

create table if not exists role (
    id bigint generated by default as identity primary key,
    role_name varchar(255) not null
);

create table if not exists cv (
    id bigint generated by default as identity primary key,
    file_name varchar(255)
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    address varchar(255),
    description varchar(500),
    email varchar(255) not null unique,
    email_verified boolean not null default false,
    email_verified_at timestamp null,
    full_name varchar(255) not null,
    image varchar(255),
    password varchar(255) not null,
    phone_number varchar(255),
    status int not null default 0,
    role_id bigint,
    cv_id bigint,
    constraint fk_users_role foreign key (role_id) references role (id),
    constraint fk_users_cv foreign key (cv_id) references cv (id)
);

create table if not exists company (
    id bigint generated by default as identity primary key,
    address varchar(255),
    description text,
    email varchar(255),
    logo varchar(255),
    company_name varchar(255) not null,
    phone_number varchar(255),
    status int not null default 1,
    user_id bigint not null unique,
    constraint fk_company_user foreign key (user_id) references users (id)
);

create table if not exists recruitment (
    id bigint generated by default as identity primary key,
    address varchar(255),
    description text,
    experience varchar(255),
    quantity int not null,
    ranks varchar(255),
    salary varchar(255),
    title varchar(255) not null,
    type varchar(255),
    deadline varchar(255),
    view int not null default 0,
    status int not null default 1,
    created_at varchar(255),
    company_id bigint not null,
    category_id bigint not null,
    constraint fk_recruitment_company foreign key (company_id) references company (id),
    constraint fk_recruitment_category foreign key (category_id) references category (id)
);

create table if not exists follow_company (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    user_id bigint not null,
    constraint fk_follow_company_company foreign key (company_id) references company (id),
    constraint fk_follow_company_user foreign key (user_id) references users (id)
);

create table if not exists save_job (
    id bigint generated by default as identity primary key,
    recruitment_id bigint not null,
    user_id bigint not null,
    constraint fk_save_job_recruitment foreign key (recruitment_id) references recruitment (id),
    constraint fk_save_job_user foreign key (user_id) references users (id)
);

create table if not exists applypost (
    id bigint generated by default as identity primary key,
    name_cv varchar(255),
    text varchar(1000),
    status int not null default 0,
    recruitment_id bigint not null,
    user_id bigint not null,
    created_at varchar(255),
    constraint fk_applypost_recruitment foreign key (recruitment_id) references recruitment (id),
    constraint fk_applypost_user foreign key (user_id) references users (id)
);

create table if not exists reset_token (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    expired_time timestamp not null,
    created_at timestamp not null,
    type varchar(20) not null default 'VERIFICATION',
    user_id bigint not null,
    constraint fk_reset_token_user foreign key (user_id) references users (id)
);

-- Indexes on FK columns for query performance
create index if not exists idx_users_role_id on users (role_id);
create index if not exists idx_recruitment_company_id on recruitment (company_id);
create index if not exists idx_recruitment_category_id on recruitment (category_id);
create index if not exists idx_follow_company_user_id on follow_company (user_id);
create index if not exists idx_follow_company_company_id on follow_company (company_id);
create index if not exists idx_save_job_user_id on save_job (user_id);
create index if not exists idx_save_job_recruitment_id on save_job (recruitment_id);
create index if not exists idx_applypost_user_id on applypost (user_id);
create index if not exists idx_applypost_recruitment_id on applypost (recruitment_id);
create index if not exists idx_reset_token_user_id on reset_token (user_id);

-- Unique constraints to prevent duplicate follows/saves
alter table follow_company drop constraint if exists uq_follow_company_user_company;
alter table follow_company add constraint uq_follow_company_user_company unique (user_id, company_id);
alter table save_job drop constraint if exists uq_save_job_user_recruitment;
alter table save_job add constraint uq_save_job_user_recruitment unique (user_id, recruitment_id);

-- Migrate: add type column and composite unique if upgrading from earlier schema
alter table reset_token add column if not exists type varchar(20) not null default 'VERIFICATION';
alter table reset_token drop constraint if exists reset_token_user_id_key;
do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'uq_reset_token_user_type' and conrelid = 'reset_token'::regclass
    ) then
        alter table reset_token add constraint uq_reset_token_user_type unique (user_id, type);
    end if;
end $$;
