-- H2-compatible test schema (mirrors main schema.sql but safe for fresh in-memory DB)
create table if not exists category (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    number_choose int not null default 0
);

create table if not exists role (
    id bigint generated by default as identity primary key,
    role_name varchar(255) not null
);

create table if not exists cv (
    id bigint generated by default as identity primary key,
    file_name varchar(255)
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    address varchar(255),
    description varchar(500),
    email varchar(255) not null unique,
    email_verified boolean not null default false,
    email_verified_at timestamp null,
    full_name varchar(255) not null,
    image varchar(255),
    password varchar(255) not null,
    phone_number varchar(255),
    status int not null default 0,
    role_id bigint,
    cv_id bigint,
    constraint fk_users_role foreign key (role_id) references role (id),
    constraint fk_users_cv foreign key (cv_id) references cv (id)
);

create table if not exists company (
    id bigint generated by default as identity primary key,
    address varchar(255),
    description text,
    email varchar(255),
    logo varchar(255),
    company_name varchar(255) not null,
    phone_number varchar(255),
    status int not null default 1,
    user_id bigint not null unique,
    constraint fk_company_user foreign key (user_id) references users (id)
);

create table if not exists recruitment (
    id bigint generated by default as identity primary key,
    address varchar(255),
    description text,
    experience varchar(255),
    quantity int not null,
    ranks varchar(255),
    salary varchar(255),
    title varchar(255) not null,
    type varchar(255),
    deadline varchar(255),
    view int not null default 0,
    status int not null default 1,
    created_at varchar(255),
    company_id bigint not null,
    category_id bigint not null,
    constraint fk_recruitment_company foreign key (company_id) references company (id),
    constraint fk_recruitment_category foreign key (category_id) references category (id)
);

create table if not exists follow_company (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    user_id bigint not null,
    constraint fk_follow_company_company foreign key (company_id) references company (id),
    constraint fk_follow_company_user foreign key (user_id) references users (id)
);

create table if not exists save_job (
    id bigint generated by default as identity primary key,
    recruitment_id bigint not null,
    user_id bigint not null,
    constraint fk_save_job_recruitment foreign key (recruitment_id) references recruitment (id),
    constraint fk_save_job_user foreign key (user_id) references users (id)
);

create table if not exists applypost (
    id bigint generated by default as identity primary key,
    name_cv varchar(255),
    text varchar(1000),
    status int not null default 0,
    recruitment_id bigint not null,
    user_id bigint not null,
    created_at varchar(255),
    constraint fk_applypost_recruitment foreign key (recruitment_id) references recruitment (id),
    constraint fk_applypost_user foreign key (user_id) references users (id)
);

create table if not exists reset_token (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    expired_time timestamp not null,
    created_at timestamp not null,
    user_id bigint not null unique,
    constraint fk_reset_token_user foreign key (user_id) references users (id)
);

